esphome:
  name: wavinahc9000v3
  friendly_name: wavinahc9000v3

esp32:
  board: esp32dev
  framework:
    type: esp-idf

external_components:
  - source: github://heinekmadsen/esphome_wavinahc9000v3@restart
    components: [wavin_ahc9000]
    refresh: 0s

logger:
  level: DEBUG
  logs:
    wavin_ahc9000: DEBUG

uart:
  id: uart_wavin
  # Prefer stable UART pins (e.g. 16/17) to avoid strapping pin issues
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 38400
  stop_bits: 1
  parity: NONE

wavin_ahc9000:
  id: wavin
  uart_id: uart_wavin
  # Regular polling interval; optionally lower temporarily for quicker discovery
  update_interval: 5s
  # Optional: speed up initial discovery (uncomment briefly)
  # poll_channels_per_cycle: 8
  # update_interval: 2s
  allow_mode_writes: false
  # Optional per-channel friendly names used in generated YAML suggestions and chunk sensors
  # Provide any subset (1..16). Missing entries fallback to "Zone N".
  channel_01_friendly_name: "Bedroom"
  channel_02_friendly_name: "Living Room"
  channel_03_friendly_name: "Kitchen"
  # channel_04_friendly_name: "Office"
  # ... add more as needed up to channel_16_friendly_name

# Onboarding helper package (manual enable/disable)
# Uncomment the yaml_generator include while you want the YAML suggestion sensors & services.
# Comment it again later to keep the runtime entity list small.
packages:
  # yaml_generator: !include packages/yaml_generator.yaml
  # wavin_debug: !include packages/wavin_debug_services.yaml

climate:
  # Single channel climate using channel 1 (friendly name -> Bedroom)
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Bedroom"
    channel: 1
  # Group climate combining channels 2 & 3. Since both have friendly names,
  # the generated group suggestion will use "Living Room & Kitchen".
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Living Area"  # You can override; suggestion would be auto-composed
    members: [2,3]

sensor:
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Bedroom Battery"
    channel: 1
    type: battery
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Bedroom Temperature"
    channel: 1
    type: temperature

wifi:
  ssid: "<your-ssid>"
  password: "<your-password>"

ota:
