esphome:
  name: wavinahc9000v3
  friendly_name: wavinahc9000v3

esp32:
  board: esp32dev
  framework:
    type: esp-idf

external_components:
  - source: github://heinekmadsen/esphome_wavinahc9000v3@main
    components: [wavin_ahc9000]

logger:
  level: DEBUG
  logs:
    wavin_ahc9000: DEBUG

uart:
  id: uart_wavin
  # Prefer stable UART pins (e.g. 16/17) to avoid strapping pin issues
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 38400
  stop_bits: 1
  parity: NONE

wavin_ahc9000:
  id: wavin
  uart_id: uart_wavin
  update_interval: 5s
  allow_mode_writes: false

climate:
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Zone 1"
    channel: 1
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Living Area"
    members: [2,3]

sensor:
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Zone 1 Battery"
    channel: 1

button:
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Repair CH1"
    channel: 1
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Repair CH9"
    channel: 9
  # Extended repair clears additional flags that may lock the thermostat keys
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Repair CH1 (Extended)"
    channel: 1
    extended: true
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Repair CH9 (Extended)"
    channel: 9
    extended: true
  # Aggressive repair clears bits 3..6 (avoids mode bits). Use only if extended fails.
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Repair CH1 (Aggressive)"
    channel: 1
    aggressive: true
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Repair CH9 (Aggressive)"
    channel: 9
    aggressive: true
  # Normalize to factory-like baseline (0x4000 for HEAT or 0x4001 for OFF)
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Normalize CH1 -> HEAT"
    channel: 1
    normalize: true
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Normalize CH1 -> OFF"
    channel: 1
    normalize: true
    normalize_off: true
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Normalize CH9 -> HEAT"
    channel: 9
    normalize: true
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    name: "Normalize CH9 -> OFF"
    channel: 9
    normalize: true
    normalize_off: true

wifi:
  ssid: "<your-ssid>"
  password: "<your-password>"

ota:

api:
