esphome:
  name: wavin-gen

esp32:
  board: esp32dev
  framework:
    type: esp-idf

external_components:
  - source: github://heinekmadsen/esphome_wavinahc9000v3@restart
    components: [wavin_ahc9000]
    refresh: 0s

logger:
  level: DEBUG
  logs:
    wavin_ahc9000: DEBUG

uart:
  id: uart_wavin
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 38400
  stop_bits: 1
  parity: NONE

wavin_ahc9000:
  id: wavin
  uart_id: uart_wavin
  update_interval: 5s
  # Speed up initial discovery temporarily (optional):
  # poll_channels_per_cycle: 8
  # update_interval: 2s
  # Friendly names (optional; only include channels you want renamed)
  channel_01_friendly_name: "Bedroom"
  channel_02_friendly_name: "Living Room"
  channel_03_friendly_name: "Kitchen"

packages:
  yaml_generator: !include packages/yaml_generator.yaml

# (Optional) readiness indicator so you know when to publish chunks
binary_sensor:
  - platform: wavin_ahc9000
    wavin_ahc9000_id: wavin
    type: yaml_ready
    name: "Wavin YAML Ready"

api:
  services:
    - service: force_generate_now
      then:
        - lambda: |-
            id(wavin).generate_yaml_suggestion();

wifi:
  ssid: "<your-ssid>"
  password: "<your-password>"

ota:
